kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.anfisa.name }}-anfisa-json
  namespace: {{ .Values.anfisa.project }}
data:
  anfisa.json: |
    {
        "file-path-def": {"WORK": "/anfisa/a-setup"},
        "host": "0.0.0.0",
        "port": 3041,
        "html-base": "/app",
        "html-title": "Anfisa v7 in Docker",
        "data-vault": "${WORK}/vault",
        "run-options": [],
        "run-modes": [],
        "job-vault-check-period": 30,
        "igv-dir": "/anfisa/anfisa/igv.dir",
        "--solutions": {
            "panels": {
                "Symbol": {
                    "dir": "${WORK}/panels/Symbol"
                }
            }
        },
        "export": {
            "--URL_to_load":
                "https://www.dropbox.com/s/4dvunn3dusqc636/SEQaBOO_output_template_20190317.xlsx",
            "excel-template": "${WORK}/export/SEQaBOO_output_template_20190317.xlsx",
            "work-dir": "${WORK}/export/work"
        },
        "sphinx-doc-sets": [
            {
                "id": "dev",
                "title": "Anfisa Installation&Administration Documentation",
                "url": "https://foromeplatform.github.io/documentation/anfisa-dev.v0.7/",
                "source": "${HOME}/doc/dev/",
                "build": "${WORK}/doc/dev/",
                "path": "doc/dev/"
            },
            {
                "id": "user",
                "title": "Anfisa User Documentation",
                "url": "https://foromeplatform.github.io/documentation/anfisa-user.v0.7/",
                "source": "${HOME}/doc/user/",
                "build": "${WORK}/doc/user/",
                "path": "doc/user/"
            }
        ],
        "dir-files": [
            ["/ui/images", "${HOME}/int_ui/images"],
            ["/ui", "${WORK}/ui"],
            ["/doc/", "${WORK}/doc/"],
            ["/excel", "${WORK}/export/work"]],

        "mirror-ui": ["${HOME}/int_ui/files", "${WORK}/ui"],
        "doc-report-css": "${HOME}/int_ui/files/report.css",
        "doc-pygments-css": "${HOME}/int_ui/files/py_pygments.css",
        "druid": {
            "vault-prefix": "demo_v6",
            "index": "http://anfisa-druid-coordinator:8081/druid/indexer/v1/task",
            "query": "http://router:80/druid/v2",
            "sql":   "http://router:80/druid/v2/sql",
            "coord": "http://anfisa-druid-coordinator:8081/druid/coordinator/v1",
            "copydir": "/data/anfisa"
        },

        "mongo-host": "anfisa-mongodb",
        "mongo-port": 27017,
        "mongo-db": "Anfisa1",
        "logging": {
            "version": 1,
            "disable_existing_loggers": false,
            "formatters": {
                    "standard": {
                    "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
                }
            },
            "handlers": {
                "default": {
                    "level": "INFO",
                    "formatter": "standard",
                    "class": "logging.FileHandler",
                    "filename": "${WORK}/logs/anfisa.log"
                }
            },
            "loggers": {
                "": {
                    "handlers": ["default"],
                    "level": "INFO",
                    "propagate": true
                }
            }
        }
    }
