apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: anfisa-backend
  labels:
    app: {{ .Values.anfisa.name }}
spec:
  host: >-
    {{ .Values.ingress.host }}
  path: /app
  to:
    kind: Service
    name: anfisa-backend
    weight: 100
  port:
    targetPort: anfisa-backend
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  wildcardPolicy: None