apiVersion: v1
kind: Service
metadata:
  name: anfisa-backend
  labels:
    app: {{ .Values.anfisa.name }}
spec:
  ports:
  - name: anfisa-backend
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.anfisa.name }}
  sessionAffinity: None
  type: ClusterIP